import type { Meta, StoryObj } from '@storybook/react';

import QuestionHistory from './question-history';
import { Suspense } from 'react';

function QuestionHistoryStory({ recentAnswers }: { recentAnswers: any[] }) {
  return (
    <Suspense>
      <div className="grid grid-cols-12">
        <QuestionHistory className="col-span-4" recentAnswers={recentAnswers} />
      </div>
    </Suspense>
  );
}

const meta = {
  component: QuestionHistoryStory,
} satisfies Meta<typeof QuestionHistoryStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    recentAnswers: [
      {
        uid: 'cm8lq0t5a00084epgpsqq75ap',
        createdAt: '2025-03-23T14:16:06.287Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: true,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'dh3982dh893ucb98nc90-cnuw2-xchmovkd',
        updatedAt: '2025-03-23T14:16:06.287Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'dh3982dh893ucb98nc90-cnuw2-xchmovkd',
          question: 'What is Git?',
          createdAt: '2025-03-14T17:15:28.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'what-is-git',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
      {
        uid: 'cm8lq0t5a00094epgnckxio8l',
        createdAt: '2025-03-23T14:16:06.287Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: true,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'dn3u29x98n23n9cm0c3-d32nuixwenciub',
        updatedAt: '2025-03-23T14:16:06.287Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'dn3u29x98n23n9cm0c3-d32nuixwenciub',
          question: 'Which of these is a programming loop?',
          createdAt: '2025-03-14T17:17:04.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'which-programming-loop',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
      {
        uid: 'cm8lq0t5a00074epgzp0gf4uj',
        createdAt: '2025-03-23T14:16:06.287Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: true,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'fj9348dhj2839h8d7wj9c0-dwn89nb2ubuc8w',
        updatedAt: '2025-03-23T14:16:06.287Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'fj9348dhj2839h8d7wj9c0-dwn89nb2ubuc8w',
          question: 'What is a function in programming?',
          createdAt: '2025-03-14T17:14:25.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'what-is-a-function-programming',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
      {
        uid: 'cm8lq00k400054epgdazdm5kj',
        createdAt: '2025-03-23T14:15:29.236Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: false,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'dh3982dh893ucb98nc90-cnuw2-xchmovkd',
        updatedAt: '2025-03-23T14:15:29.236Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'dh3982dh893ucb98nc90-cnuw2-xchmovkd',
          question: 'What is Git?',
          createdAt: '2025-03-14T17:15:28.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'what-is-git',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
      {
        uid: 'cm8lq00k400064epg36nakibm',
        createdAt: '2025-03-23T14:15:29.236Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: true,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'dn3u29x98n23n9cm0c3-d32nuixwenciub',
        updatedAt: '2025-03-23T14:15:29.236Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'dn3u29x98n23n9cm0c3-d32nuixwenciub',
          question: 'Which of these is a programming loop?',
          createdAt: '2025-03-14T17:17:04.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'which-programming-loop',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
    ],
  },
};

export const Empty: Story = {
  args: {
    recentAnswers: [],
  },
};
