import type { Meta, StoryObj } from '@storybook/react';

import QuestionHistory from './question-history';
import { Suspense } from 'react';

function QuestionHistoryStory({ recentAnswers }: { recentAnswers: any[] }) {
  return (
    <Suspense>
      <div className="grid grid-cols-12">
        <QuestionHistory className="col-span-4" recentAnswers={recentAnswers} />
      </div>
    </Suspense>
  );
}

const meta = {
  component: QuestionHistoryStory,
} satisfies Meta<typeof QuestionHistoryStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    recentAnswers: [
      {
        uid: 'cm8lq0t5a00084epgpsqq75ap',
        createdAt: '2025-03-23T14:16:06.287Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: true,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'dh3982dh893ucb98nc90-cnuw2-xchmovkd',
        updatedAt: '2025-03-23T14:16:06.287Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'dh3982dh893ucb98nc90-cnuw2-xchmovkd',
          question: 'What is Git?',
          createdAt: '2025-03-14T17:15:28.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'what-is-git',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
      {
        uid: 'cm8lq0t5a00094epgnckxio8l',
        createdAt: '2025-03-23T14:16:06.287Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: true,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'dn3u29x98n23n9cm0c3-d32nuixwenciub',
        updatedAt: '2025-03-23T14:16:06.287Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'dn3u29x98n23n9cm0c3-d32nuixwenciub',
          question: 'Which of these is a programming loop?',
          createdAt: '2025-03-14T17:17:04.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'which-programming-loop',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
      {
        uid: 'cm8lq0t5a00074epgzp0gf4uj',
        createdAt: '2025-03-23T14:16:06.287Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: true,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'fj9348dhj2839h8d7wj9c0-dwn89nb2ubuc8w',
        updatedAt: '2025-03-23T14:16:06.287Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'fj9348dhj2839h8d7wj9c0-dwn89nb2ubuc8w',
          question: 'What is a function in programming?',
          createdAt: '2025-03-14T17:14:25.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'what-is-a-function-programming',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
      {
        uid: 'cm8lq00k400054epgdazdm5kj',
        createdAt: '2025-03-23T14:15:29.236Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: false,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'dh3982dh893ucb98nc90-cnuw2-xchmovkd',
        updatedAt: '2025-03-23T14:15:29.236Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'dh3982dh893ucb98nc90-cnuw2-xchmovkd',
          question: 'What is Git?',
          createdAt: '2025-03-14T17:15:28.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'what-is-git',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
      {
        uid: 'cm8lq00k400064epg36nakibm',
        createdAt: '2025-03-23T14:15:29.236Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: true,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'dn3u29x98n23n9cm0c3-d32nuixwenciub',
        updatedAt: '2025-03-23T14:15:29.236Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'dn3u29x98n23n9cm0c3-d32nuixwenciub',
          question: 'Which of these is a programming loop?',
          createdAt: '2025-03-14T17:17:04.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'which-programming-loop',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
      {
        uid: 'cm8lq00k400044epgkrcuwi3i',
        createdAt: '2025-03-23T14:15:29.236Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: true,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'fj9348dhj2839h8d7wj9c0-dwn89nb2ubuc8w',
        updatedAt: '2025-03-23T14:15:29.236Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'fj9348dhj2839h8d7wj9c0-dwn89nb2ubuc8w',
          question: 'What is a function in programming?',
          createdAt: '2025-03-14T17:14:25.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'what-is-a-function-programming',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
      {
        uid: 'cm8kowo6700034epgq9mvxmej',
        createdAt: '2025-03-22T20:57:07.423Z',
        timeTaken: 175,
        userAnswerUid: '5pgm8kfznb5',
        correctAnswer: true,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: '5pgm8kfznb7',
        updatedAt: '2025-03-22T20:57:07.423Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: '5pgm8kfznb7',
          question: "What does the HTTP status code '200' mean?",
          createdAt: '2025-03-22T16:47:29.727Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: '',
          answerResource: null,
          correctAnswer: '5pgm8kfznb5',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'what-does-http-200-mean',
          slugGenerated: true,
          description: null,
          title: "What does the HTTP status code '200' mean?",
          questionType: 'SIMPLE_MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo:
            "<p>\nTypically, HTTP codes that begin with '2' indicate that the request was successfully received, understood, and accepted.\n</p>\n<br />\n<p>\nThe HTTP status code '200' means the request was successful, indicating that the server returned the requested resource.\n</p>\n<br />\n<span>\nView the HTTP cat for '200' <a style=\"text-decoration: 'underline'\" href=\"http://http.cat/200\" target=\"_blank\">here!</a>\n</span>",
          tags: [
            {
              questionId: '5pgm8kfznb7',
              tagId: '136bm5n0g45g',
              tag: { uid: '136bm5n0g45g', name: 'http' },
            },
            {
              questionId: '5pgm8kfznb7',
              tagId: '5pgm8kfznbb',
              tag: { uid: '5pgm8kfznbb', name: 'http-codes' },
            },
            {
              questionId: '5pgm8kfznb7',
              tagId: '5pgm8kfznbd',
              tag: { uid: '5pgm8kfznbd', name: 'status-codes' },
            },
          ],
        },
      },
      {
        uid: 'cm8kj11o100004epg0rxcfjxv',
        createdAt: '2025-03-22T18:12:33.842Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: true,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'fj9348dhj2839h8d7wj9c0-dwn89nb2ubuc8w',
        updatedAt: '2025-03-22T18:12:33.842Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'fj9348dhj2839h8d7wj9c0-dwn89nb2ubuc8w',
          question: 'What is a function in programming?',
          createdAt: '2025-03-14T17:14:25.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'what-is-a-function-programming',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
      {
        uid: 'cm8kj11o200014epg8u3yrhvk',
        createdAt: '2025-03-22T18:12:33.842Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: false,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'dh3982dh893ucb98nc90-cnuw2-xchmovkd',
        updatedAt: '2025-03-22T18:12:33.842Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'dh3982dh893ucb98nc90-cnuw2-xchmovkd',
          question: 'What is Git?',
          createdAt: '2025-03-14T17:15:28.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'what-is-git',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
      {
        uid: 'cm8kj11o200024epgs9k48d2x',
        createdAt: '2025-03-22T18:12:33.842Z',
        timeTaken: 0,
        userAnswerUid: null,
        correctAnswer: true,
        userUid: '3a57d7e8-8b80-483b-93d0-70fe1f06b0c0',
        questionUid: 'dn3u29x98n23n9cm0c3-d32nuixwenciub',
        updatedAt: '2025-03-22T18:12:33.842Z',
        questionDate: '',
        difficulty: 'EASY',
        question: {
          uid: 'dn3u29x98n23n9cm0c3-d32nuixwenciub',
          question: 'Which of these is a programming loop?',
          createdAt: '2025-03-14T17:17:04.000Z',
          updatedAt: '2025-03-23T20:17:51.904Z',
          questionDate: 'NULL',
          answerResource: null,
          correctAnswer: 'NULL',
          codeSnippet: null,
          hint: null,
          dailyQuestion: false,
          difficulty: 'BEGINNER',
          customQuestion: false,
          slug: 'which-programming-loop',
          slugGenerated: true,
          description: null,
          title: null,
          questionType: 'MULTIPLE_CHOICE',
          expectedParams: null,
          functionName: null,
          returnType: null,
          testCases: null,
          nextQuestionSlug: null,
          previousQuestionSlug: null,
          isPremiumQuestion: false,
          afterQuestionInfo: null,
          tags: [],
        },
      },
    ],
  },
};

export const Empty: Story = {
  args: {
    recentAnswers: [],
  },
};
