-- CreateEnum
CREATE TYPE "UserTimeSpendingPerDay" AS ENUM ('LESS_THAN_5_MINUTES', 'BETWEEN_5_AND_15_MINUTES', 'BETWEEN_15_AND_30_MINUTES', 'BETWEEN_30_AND_60_MINUTES', 'MORE_THAN_60_MINUTES');

-- AlterTable
ALTER TABLE "Users" ADD COLUMN     "hasSent7DayNoChallengeEmail" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "timeSpendingPerDay" "UserTimeSpendingPerDay" DEFAULT 'LESS_THAN_5_MINUTES';
